### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by johantiden** [johantiden/myfeed#8]
Collecting ideas for filters here.

- quiz
- ”Flag if 2 or more click-baity terms appear. ”

**Comment by johantiden** [comment]
Stockholmstestet

**Comment by johantiden** [comment]
Reddit::Hockey

**Comment by johantiden** [comment]
Reddit::RocketLeague

**Comment by johantiden** [comment]
r/h3h3productions

**Comment by larsjoakimgrahn** [comment]
Need more fidn filters plz

**Comment by johantiden** [comment]
Covid, corona, sars-cov and virus, etc are now tagged :+1: @larsjoakimgrahn 
www.tidn.se
